#******************************************************************************#
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: xtang <marvin@42.fr>                       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/10/16 17:11:57 by xtang             #+#    #+#              #
#    Updated: 2019/10/17 16:51:21 by xtang            ###   ########.fr        #
#                                                                              #
#******************************************************************************#

NAME = ft_display_file
C_FILES = ft_display_file.c

.PHONY: all clean fclean

all: 
	@gcc -Wall -Wextra -Werror -o $(NAME) $(C_FILES)

clean: 
	@rm -f *.o

fclean:
	@rm -f $(NAME);
